---
apiVersion: v1
kind: Service
metadata:
  name: smi-conformance
  namespace: meshplay
  labels:
    app.kubernetes.io/name: smi-conformance
spec:
  type: LoadBalancer
  ports:
    - port: 10011
      targetPort: grpc
      protocol: TCP
      name: smi-conformance
  selector:
    app.kubernetes.io/name: smi-conformance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smi-conformance
  namespace: meshplay
  labels:
    app.kubernetes.io/name: smi-conformance
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smi-conformance
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smi-conformance
    spec:
      serviceAccountName: meshplay-operator
      containers:
        - name: smi-conformance
          image: "khulnasoft/learn-khulnasoft:smi"
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 10011
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1000Mi
            requests:
              cpu: 200m
              memory: 500Mi
      restartPolicy: Always
