apiVersion: split.smi-spec.io/v1alpha4
kind: TrafficSplit
metadata:
  name: server-split
  namespace: <NAMESPACE>
spec:
  service: app-svc
  backends:
  - service: app-b
    weight: 1
  - service: app-c
    weight: 0