apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httproutegroups.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
status:
  acceptedNames:
    kind: HTTPRouteGroup
    shortNames: 
      - htr
    plural: httproutegroups
    singular: httproutegroup