apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
  namespace: <NAMESPACE>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
  namespace: <NAMESPACE>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-c
  namespace: <NAMESPACE>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  namespace: <NAMESPACE>
status:
  readyReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
  namespace: <NAMESPACE>
status:
  readyReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c-deployment
  namespace: <NAMESPACE>
status:
  readyReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: <NAMESPACE>
spec:
  type: NodePort
  selector:
    app: app-a
  ports:
  - name: http
    protocol: TCP
    port: 9091
    # targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: <NAMESPACE>
spec:
  type: NodePort
  selector:
    app: app-b
  ports:
  - name: http
    protocol: TCP
    port: 9091
    # targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-c
  namespace: <NAMESPACE>
spec:
  type: NodePort
  selector:
    app: app-c
  ports:
  - name: http
    protocol: TCP
    port: 9091
    # targetPort: 9091