apiVersion: specs.smi-spec.io/v1alpha4
kind: HTTPRouteGroup
metadata:
  name: http-rg
  namespace: <NAMESPACE>
matches:
- name: testMatch
  pathRegex: /metrics
  methods: ["*"]
---
apiVersion: access.smi-spec.io/v1alpha3
kind: TrafficTarget
metadata:
  name: service-targets
  namespace: <NAMESPACE>
spec:
  destination:
    kind: ServiceAccount
    name: service-b
    namespace: <NAMESPACE>
    port: "9091"
  sources:
  - kind: ServiceAccount
    name: service-a
    namespace: <NAMESPACE>
  rules:
  - kind: HTTPRouteGroup
    name: http-rg
    matches:
    - testMatch