apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smi-conformance.name" . }}
  namespace: {{ include "smi-conformance.namespace" . }}
  labels:
    {{- include "smi-conformance.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "smi-conformance.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "smi-conformance.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "smi-conformance.serviceAccount" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always