apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traffictargets.access.smi-spec.io
spec:
  group: access.smi-spec.io
status:
  acceptedNames:
    kind: TrafficTarget
    shortNames: 
      - tt
    plural: traffictargets
    singular: traffictarget