---
apiVersion: specs.smi-spec.io/v1alpha4
kind: TCPRoute
metadata:
  name: service-tcp-route
  namespace: <NAMESPACE>
spec:
  matches:
    ports: []
---
apiVersion: access.smi-spec.io/v1alpha3
kind: TrafficTarget
metadata:
  name: service-targets
  namespace: <NAMESPACE>
spec:
  destination:
    kind: ServiceAccount
    name: service-b
    namespace: <NAMESPACE>
  sources:
  - kind: ServiceAccount
    name: service-a
    namespace: <NAMESPACE>
  rules:
  - kind: TCPRoute
    name: service-tcp-route
